config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "favorites", to: "favorites#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users do
    resources :favorites, only: [:create, :delete]
  end
  resources :recipes, only: [:index, :show, :edit, :update, :delete]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  validates :username,  presence: true,
                        length: {minimum: 4, maximum: 25}
  has_many :favorites
  has_many :favorite_recipes, through: :favorites, source: :recipe

  def favorited?(recipe) 
    favorites.find_by(recipe_id: recipe["id"]) ? true : false
  end

  def self.from_omniauth(auth)
    # find user and add provider/uid if it already exists but has not been linked
    if existing_user = find_by(email: auth.info.email)
      existing_user.update_attributes(provider: auth.provider, uid: auth.uid) if existing_user.provider.nil? && existing_user.uid.nil?
    end
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.first_name
      user.email = auth.info.email
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def render_not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.favorite_recipes
  end

  def create
  end

  def destroy
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include RecipesHelper

  def index
    @search = params[:search]
    response = recipe_search_results_for(@search)
    search_results = get_recipe_array(response)
    @recipes = search_results.paginate(page: params[:page], per_page: 16)
  end

  def show
    # if the recipe exists in the database load the recipe
    if Recipe.exists?(params[:id])
      @recipe = Recipe.find(params[:id])
    else
      # retrieve the recipe from the api
      # then save the recipe to the database to help reduce api calls in the future
      response = recipe_info_for(params[:id])
      render_not_found if response["code"] == 404 || response["status"] == 404
      @recipe = Recipe.new
      @recipe.from_json(trim_response(response).to_json).save
    end

    @nutrition = @recipe.nutrition["nutrients"]
  end

  private
    # parse api json data into an array that the view can iterate over
    def get_recipe_array(json)
      recipes = JSON.parse(json.body)
      recipes["results"]
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_oauth2_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.order(:id).paginate(page: params[:page], per_page: 16)
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user == @user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  # spoonacular api base url
  BASE_URL = "https://api.spoonacular.com"
  RECIPE_SEARCH_URL = "#{BASE_URL}/recipes/search?query="
  RECIPE_INFORMATION_URL = "#{BASE_URL}/recipes/477032/information?includeNutrition=false"

  # Image sizes that are available via the spoonacular api
  IMAGE_SIZES = {
    thumbnail: "90x90",
    xsmall: "240x150",
    small: "312x150",
    medium: "312x231",
    large: "480x360",
    xlarge: "556x370",
    source: "636x393"
  }

  # builds an image tag based on spoonacular requirements
  # https://spoonacular.com/food-api/docs#Show-Images
  def image_for(id, size=:source)
    image_tag "https://spoonacular.com/recipeImages/#{id}-#{IMAGE_SIZES[size]}"
  end

  # returns recipes that contain the given search term, number of results can be between 1-100
  def recipe_search_results_for(search, number=100)
    Faraday.get "#{RECIPE_SEARCH_URL}#{search}&number=#{number}&apiKey=#{spoonacular_key}"
  end

  # retrieve recipe, returns faraday response object parsed as json
  def recipe_info_for(id)
    response = Faraday.get("https://api.spoonacular.com/recipes/#{id}/information?includeNutrition=true&apiKey=#{spoonacular_key}")
    JSON.parse response.body
  end

  def trim_response(response)
    response.slice("id", "vegetarian", "vegan", "glutenFree", "dairyFree", "veryHealthy", "cheap", "sustainable", "veryPopular", "sourceUrl", "aggregateLikes", "creditsText", "license", "sourceName", "pricePerServing", "title", "readyInMinutes", "servings", "image", "imageType", "cuisines", "dishTypes", "diets", "occasions", "winePairing", "instructions", "preparationMinutes", "cookingMinutes", "summary", "analyzedInstructions", "extendedIngredients", "nutrition")
  end

  private
  def spoonacular_key
    Rails.application.credentials.spoonacular[:api_key]
  end
 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_form.html.erb
<% if current_user.favorited?(recipe) %>
  <%= render "shared/favorite_icon_filled" %>
<% else %>
  <%= render "shared/favorite_icon_outline" %>
<% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/index.html.erb
<div class="container">
  <h1>My Favorites</h1>
  <%= render "recipes/recipes_list" %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="subtext">
      <!-- Site logo attribution text -->
      <div> Logo icon made by <a href="https://www.flaticon.com/authors/those-icons" title="Those Icons">Those Icons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <!-- Togglable sidebar naviation menu -->
  <%= render "layouts/sidebar" %>

  <!-- navigation search form, only shows after being toggled on -->
  <div id="nav-search">
    <div class="nav-search-container">
      <%= form_with url: recipes_path, method: :get, local: true, class: "nav-search-form" do |f| %>
        <div class="form-group">
          <%= f.label :search, class: "sr-only" %>
          <div class="nav-search-box">
            <%= f.text_field :search, placeholder: "What would you like to eat...?" %>
            <!-- Allow user to close the search bar -->
            <%= button_tag type: "button", onclick: "closeNavSearch()", id: "close-nav-search", class: "nav-btn" do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/>
                <path d="M0 0h24v24H0z" fill="none"/>
              </svg>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="main-nav">
    <div class="nav-container">
      <%= button_tag onclick: "expandNav()", class: "nav-btn", id: "mobile-nav-expand" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M3 18h18v-2H3v2zm0-5h18v-2H3v2zm0-7v2h18V6H3z"/></svg>
      <% end %>
      <%= link_to root_path, class: "logo-container" do %>
        <div class="logo"><%= render "layouts/logo" %></div>
        <span class="logo-text">cookbook</span>
      <% end %>
    </div>

    <div class="nav-container">
      <% unless user_signed_in? %>
        <%= link_to "Log in", new_user_session_path, class: "btn" %>
        <%= link_to "Sign up" , new_user_registration_path, class: "btn btn-primary" %>
      <% else %>
        <%= link_to user_path(current_user), class: "nav-btn" do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>
        <% end %>
      <% end %>
      <%= button_tag onclick: "expandNavSearch()", class: "nav-btn", id: "nav-search-expand" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
          <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
          <path d="M0 0h24v24H0z" fill="none"/>
        </svg>
      <% end %>
    </div>
  </div>

</nav>

app/views/layouts/_logo.html.erb
<!-- Website logo, moved this to a partial because the code is huge -->

<?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<g>
	<g>
		<g>
			<path d="M448,10.667C448,4.771,443.229,0,437.333,0H106.667C83.135,0,64,19.135,64,42.667v426.667
				C64,492.865,83.135,512,106.667,512h330.667c3.938,0,7.552-2.167,9.406-5.635c1.854-3.469,1.646-7.677-0.531-10.948
				c-10.563-15.844-10.563-36.323,0-52.167l-0.161-0.108c1.133-1.694,1.953-3.615,1.953-5.809V10.667z M420.375,490.667H106.667
				c-11.76,0-21.333-9.573-21.333-21.333c0-11.76,9.573-21.333,21.333-21.333h313.967
				C416.047,461.874,415.796,476.794,420.375,490.667z M426.667,426.667h-320c-7.76,0-15.052,2.083-21.333,5.729V42.667
				c0-11.76,9.573-21.333,21.333-21.333h320V426.667z"/>
			<path d="M170.667,245.115v64.219c0,17.646,14.354,32,32,32h106.667c17.646,0,32-14.354,32-32v-64.219
				c13.292-10.021,21.333-25.771,21.333-42.448c0-32.642-30.615-58.119-63.12-51.938C289.885,137.025,274.004,128,256,128
				c-18.005,0-33.888,9.026-43.549,22.732c-32.549-6.19-63.126,19.29-63.117,51.935
				C149.333,219.344,157.375,235.094,170.667,245.115z M320,309.333c0,5.885-4.781,10.667-10.667,10.667H202.667
				c-5.885,0-10.667-4.781-10.667-10.667v-10.667h128V309.333z M203.728,170.845c-0.68,3.395-1.061,6.897-1.061,10.488
				c0,5.896,4.771,10.667,10.667,10.667c5.896,0,10.667-4.771,10.667-10.667c0-17.646,14.354-32,32-32s32,14.354,32,32
				c0,5.896,4.771,10.667,10.667,10.667c5.896,0,10.667-4.771,10.667-10.667c0-3.59-0.381-7.091-1.061-10.484
				c18.083-0.893,33.07,13.839,33.061,31.818c0,11.396-5.99,21.688-16.031,27.531c-3.281,1.917-5.302,5.427-5.302,9.219v37.917H192
				v-37.917c0-3.792-2.021-7.302-5.302-9.219c-10.042-5.844-16.031-16.135-16.031-27.531
				C170.667,184.685,185.629,169.943,203.728,170.845z"/>
		</g>
	</g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>

app/views/layouts/_sidebar.html.erb
  <div id="mobile-nav">
    <div class="mobile-nav-header">
      <div class="logo"><%= render "layouts/logo" %></div>
      <span class="logo-text-sidebar">cookbook</span>
    </div>
    <ul class="mobile-nav-links"> 
      <li><%=link_to "home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Favorites", favorites_path %></li>
        <li><%= link_to "Account settings", edit_user_registration_path(current_user) %></li>
        <div class="divider"></div>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% end %>
    </ul>
  </div>
  <div id="mobile-nav-close" onclick="closeNav()"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Open+Sans&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <% unless flash.empty? %>
      <div id="flash-container">
        <div id="flash">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "flash alert alert-#{key} text-center" %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

  <%= debug(params) if Rails.env.development? %>
</html>

app/views/recipes/_diets.html.erb
        <% if @recipe.vegetarian %>
          <span class="pill pill-vegetarian">vegetarian</span>
        <% end %>
        <% if @recipe.vegan %>
          <span class="pill pill-vegan">vegan</span>
        <% end %>
        <% if @recipe.glutenFree %>
          <span class="pill pill-gluten">gluten free</span>
        <% end %>
        <% if @recipe.dairyFree %>
          <span class="pill pill-dairy">dairy free</span>
        <% end %>

app/views/recipes/_recipes_list.html.erb
    <div class="recipe-grid">
      <% @recipes.each do |recipe| %>
        <div class="recipe-card">
          <%= link_to recipe_path(recipe["id"]) do %>
            <div class="recipe-card-image">
              <%= image_for(recipe["id"], :medium) unless recipe["image"].nil? %>
            </div>
          <% end %>

          <div class="recipe-card-info">
            <h2><%= link_to recipe["title"], recipe_path(recipe["id"]) %></h2>
            <div class="recipe-card-meta">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <title>Ready in minutes</title>
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M15 1H9v2h6V1zm-4 13h2V8h-2v6zm8.03-6.61l1.42-1.42c-.43-.51-.9-.99-1.41-1.41l-1.42 1.42C16.07 4.74 14.12 4 12 4c-4.97 0-9 4.03-9 9s4.02 9 9 9 9-4.03 9-9c0-2.12-.74-4.07-1.97-5.61zM12 20c-3.87 0-7-3.13-7-7s3.13-7 7-7 7 3.13 7 7-3.13 7-7 7z"/>
              </svg>
              <span><%= recipe["readyInMinutes"] %></span>
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <title>Servings</title>
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M8.1 13.34l2.83-2.83L3.91 3.5c-1.56 1.56-1.56 4.09 0 5.66l4.19 4.18zm6.78-1.81c1.53.71 3.68.21 5.27-1.38 1.91-1.91 2.28-4.65.81-6.12-1.46-1.46-4.2-1.1-6.12.81-1.59 1.59-2.09 3.74-1.38 5.27L3.7 19.87l1.41 1.41L12 14.41l6.88 6.88 1.41-1.41L13.41 13l1.47-1.47z"/>
              </svg>
              <span><%= recipe["servings"] %></span>
              <%= render partial: "favorites/form", locals: { :recipe => recipe } %>
            </div>
          </div>

          <div class="caret">
            <%= link_to recipe_path(recipe["id"]) do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <path d="M8.59 16.59L13.17 12 8.59 7.41 10 6l6 6-6 6-1.41-1.41z"/>
                <path d="M0 0h24v24H0V0z" fill="none"/>
              </svg>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>

app/views/recipes/_search_form.html.erb
<%= form_with url: recipes_path, method: :get, local: true, class: "search-form" do |f| %>
  <div class="form-group">
    <%= f.label :search, class: "sr-only" %>
    <div class="search-box">
      <%= f.text_field :search, placeholder: "What would you like to eat...?" %>
      <%= button_tag type: "submit" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
          <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/>
          <path d="M0 0h24v24H0z" fill="none"/>
        </svg>
      <% end %>
    </div>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div class="container">
  <% unless @recipes.empty? %>
    <%= render "recipes_list" %>
  <% else %>
    <p>Sorry, there were no recipe results for “<%= @search %>”</p>
  <% end %>

  <%= will_paginate @recipes %>
</div>

app/views/recipes/show.html.erb
<article>
  <div id="recipe-image-container-mobile">
    <%= render "shared/favorite_icon_outline" %>
    <%= image_for @recipe.id, :source unless @recipe.image.nil? %>
  </div>
  <div id="recipe-content" class="container">
    <header>
      <div id="recipe-header-info">
        <div class="recipe-title">
          <h1><%= @recipe.title %></h1> 
          <span class="subtitle subtext">from
            <%= link_to @recipe.creditsText, @recipe.sourceUrl %>
          </span>
        </div>

        <%= render partial: "favorites/form", locals: { :recipe => @recipe } %>

        <div class="recipe-meta">
          <div class="info-bar">
            <div class="info-bar-item">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <title>Ready in minutes</title>
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M15 1H9v2h6V1zm-4 13h2V8h-2v6zm8.03-6.61l1.42-1.42c-.43-.51-.9-.99-1.41-1.41l-1.42 1.42C16.07 4.74 14.12 4 12 4c-4.97 0-9 4.03-9 9s4.02 9 9 9 9-4.03 9-9c0-2.12-.74-4.07-1.97-5.61zM12 20c-3.87 0-7-3.13-7-7s3.13-7 7-7 7 3.13 7 7-3.13 7-7 7z"/>
              </svg>
              <span id="ready-in-minutes" class="info-number"><%= @recipe["readyInMinutes"] %></span>
              <span class="minutes-text">Minutes</span>
            </div>
            <div class="divider"></div>
            <div class="info-bar-item">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <title>Servings</title>
                <path d="M0 0h24v24H0z" fill="none"/>
                <path d="M8.1 13.34l2.83-2.83L3.91 3.5c-1.56 1.56-1.56 4.09 0 5.66l4.19 4.18zm6.78-1.81c1.53.71 3.68.21 5.27-1.38 1.91-1.91 2.28-4.65.81-6.12-1.46-1.46-4.2-1.1-6.12.81-1.59 1.59-2.09 3.74-1.38 5.27L3.7 19.87l1.41 1.41L12 14.41l6.88 6.88 1.41-1.41L13.41 13l1.47-1.47z"/>
              </svg>
              <span id="servings" class="info-number"><%= @recipe["servings"] %></span>
              <span class="servings-text">Servings</span>
            </div>
            <div class="divider"></div>
            <div class="info-bar-item">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
                <title><%= @nutrition[0]["title"] %></title>
                <path d="M11 9H9V2H7v7H5V2H3v7c0 2.12 1.66 3.84 3.75 3.97V22h2.5v-9.03C11.34 12.84 13 11.12 13 9V2h-2v7zm5-3v8h2.5v8H21V2c-2.76 0-5 2.24-5 4z"/>
                <path d="M0 0h24v24H0z" fill="none"/>
              </svg>
              <span id="calories" class="info-number"><%= @nutrition[0]["amount"] %></span>
              <span class="calories-text"><%= @nutrition[0]["title"] %></span>
            </div>
          </div>
          <div class="diets">
            <%= render "diets" %>
          </div>
        </div>
      </div>

      <div id="recipe-image-container-desktop"> 
        <%= image_for @recipe.id, :source unless @recipe.image.nil? %>
      </div>
    </header>
    <div class="section-divider"></div>
    <section class="checklist">
      <h2>Ingredients</h2>
      <% @recipe.extendedIngredients.each_with_index do |ingredient, index| %>
        <label id="checklist-item-<%= index %>" class="checklist-item" onClick="toggleStrikethrough(id)"> <%= ingredient["originalString"] %>
          <input type="checkbox">
          <span class="custom-checkbox"></span>
        </label>
      <% end %>
    </section>

    <section class="instructions">
      <% unless @recipe.analyzedInstructions.empty? %>
      <ol>
        <h2>Instructions</h2>
        <% @recipe.analyzedInstructions.first["steps"].each do |step| %>
          <li><%= step["step"] %></li>
        <% end %>
        <ol>
      <% end %>
    </section>
  </div>
</article>

app/views/shared/_favorite_icon.html.erb
<svg class="favorite" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
</svg>

app/views/shared/_favorite_icon_filled.html.erb
<svg class="favorite" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/>
</svg>

app/views/shared/_favorite_icon_outline.html.erb
<svg class="favorite" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" width="24">
  <title>Favorite</title>
  <path d="M0 0h24v24H0z" fill="none"/>
  <path d="M16.5 3c-1.74 0-3.41.81-4.5 2.09C10.91 3.81 9.24 3 7.5 3 4.42 3 2 5.42 2 8.5c0 3.78 3.4 6.86 8.55 11.54L12 21.35l1.45-1.32C18.6 15.36 22 12.28 22 8.5 22 5.42 19.58 3 16.5 3zm-4.4 15.55l-.1.1-.1-.1C7.14 14.24 4 11.39 4 8.5 4 6.5 5.5 5 7.5 5c1.54 0 3.04.99 3.57 2.36h1.87C13.46 5.99 14.96 5 16.5 5c2 0 3.5 1.5 3.5 3.5 0 2.89-3.14 5.74-7.9 10.05z"/>
</svg>

app/views/static_pages/home.html.erb
<div id="hero">
    <div id="hero-content" class="container">
      <h1>Plan your next meal</h1>
      <%= render "recipes/search_form" %>
    </div>
</div>

app/views/users/_user.html.erb
<li><%= user.id %> - <%= user.email %></li>

app/views/users/index.html.erb
<div class="container">
  <h1>Users Index</h1>
  <ul>
    <%= render @users %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.username %></h1>
  <p>id: <%= @user.id %></p>
  <p>email: <%= @user.email %></p>
</div>